### ISSUE TITLE
[ETP-630]: Wrong dependency management without compatibility range to core in dependency management window

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.dependencymanager#30]
# Error's description
In the dependency management window, when the change version process is executed to change the version of a module that has no dependency to core (for example com.etendoerp.copilot) it tries to do the range validation even if it is null.

Adding and deleting records must be disabled, since it is a read-only window.

# Steps to reproduce the error

1. Open Module management window
2. Add copilot extensions bundle
3. In dependency management, select com.etendo.copilot and change version

# Expected behavior
Validation should not be done in case of not having a Core compatibility range.
It should not be possible to add or delete records from the toolbar.

# Affected Version 
version 1.1.0

# Other test cases
Create an automatic test to validate the java process passing the core parameters in null

**Comment by isaiasb-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.1.2](https://github.com/etendosoftware/com.etendoerp.dependencymanager/releases/tag/1.1.2) ⚡ 🚀
