### ISSUE TITLE
ETP-799: Compatibility verification issue when installing dependencies with the Dependency Manager module

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/com.etendoerp.dependencymanager#35]
**Error's description**

A bug has been identified in the compatibility verification process for dependency versions during module installation via the Dependency Manager. The issue arises even when the specified dependencies match the required versions.

For example, while attempting to install version 1.8.1 of the Copilot Extensions bundle through the Module Management window, with the Webhook Events module already installed in version 1.11.1, the installation fails. The dependency of Copilot Extensions with Webhook Events corresponds correctly to version 1.11.1, so the installation should proceed without errors.

Instead, running the Add Dependency action with all the modules of the bundle results in the following error:

"It is not possible to install the dependency com.etendoerp.webhookevents, in 1.11.1 version because it is already installed in a later version and could affect existing functionalities. If you want to install it anyway, you should downgrade this dependency to version 1.11.1 from the Dependency Management window."

This issue can occur in any similar scenario where dependencies are being installed. The provided example illustrates a specific case.

**Steps to reproduce the error**

1. Open the Module Management window in Etendo.
2. Attempt to install version 1.8.1 of the Copilot Extensions bundle.
3. Ensure that the Webhook Events module is already installed in version 1.11.1.
4. Execute the Add Dependency action for all the modules in the bundle.
5. Observe the error message.

**Expected behavior**

The installation process should proceed without issues when the dependencies' versions match the required specifications. In this example, version 1.11.1 of the Webhook Events module is compatible with the Copilot Extensions bundle.

**Affected Version**

**Dependency Manager Module**: 1.1.2

**Solution Design (optional)**

Investigate the compatibility verification logic in the Dependency Manager module. Ensure that it correctly validates the installed version of a dependency against the required version specified by the module being installed.

**Other test cases**

**Given**: A module bundle with dependencies requiring specific versions.
**When**: Installing the bundle with compatible dependencies already installed.
**Then**: The installation completes successfully without errors.

**Given**: A module bundle with dependencies requiring specific versions.
**When**: Installing the bundle with incompatible dependency versions installed.
**Then**: An appropriate error message is displayed, instructing the user to adjust the dependency version.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.1.3](https://github.com/etendosoftware/com.etendoerp.platform.extensions/releases/tag/1.1.3) ⚡ 🚀
